export const menus = [
  {
    id: 6,
    topId: 3,
    code: "DASHBOARD",
    name: "대시보드",
    nameEn: "Dashboard",
    nameKo: "대시보드",
    route: "/dashboard",
    ordinal: 1,
    visible: true,
  },
  {
    id: 7,
    topId: 4,
    code: "CONNECTOR",
    name: "수집 설정",
    nameEn: "Connector",
    nameKo: "수집 설정",
    route: "/connector",
    ordinal: 1,
    visible: false,
  },
  {
    id: 8,
    topId: 4,
    code: "PARSER",
    name: "원본 로그 파서 원본 로그 파서 원본 로그 파서 원본 로그 파서",
    nameEn: "Parser",
    nameKo: "원본 로그 파서",
    route: "/parser",
    ordinal: 2,
    visible: false,
  },
  {
    id: 46,
    topId: 4,
    code: "NORMALIZER",
    name: "정규화 파서",
    nameEn: "Normalizer",
    nameKo: "정규화 파서",
    route: "/normalizer",
    ordinal: 3,
    visible: true,
  },
  {
    id: 9,
    topId: 4,
    code: "SCHEMA",
    name: "정규화",
    nameEn: "Schema",
    nameKo: "정규화",
    route: "/schema",
    ordinal: 4,
    visible: true,
  },
  {
    id: 10,
    topId: 4,
    code: "CONNECTOR_MODEL",
    name: "수집 모델",
    nameEn: "Connector Model",
    nameKo: "수집 모델",
    route: "/connector-model",

    ordinal: 5,
    visible: true,
  },
  {
    id: 11,
    topId: 4,
    code: "EXTRACTOR_MODEL",
    name: "추출 모델",
    nameEn: "Extractor Model",
    nameKo: "추출 모델",
    route: "/extractor-model",
    ordinal: 6,
    visible: false,
  },
  {
    id: 44,
    topId: 5,
    code: "EVENT_SUMMARY",
    name: "탐지 현황",
    nameEn: "Event Summary",
    nameKo: "탐지 현황",
    route: "/event-summary",
    ordinal: 0,
    visible: false,
  },
  {
    id: 12,
    topId: 5,
    code: "EVENT",
    name: "이벤트",
    nameEn: "Event",
    nameKo: "이벤트",
    route: "/event",
    ordinal: 1,
    visible: true,
  },
  {
    id: 13,
    topId: 5,
    code: "LOG",
    name: "로그",
    nameEn: "Log",
    nameKo: "로그",
    route: "/log",
    ordinal: 2,
    visible: false,
  },
  {
    id: 14,
    topId: 5,
    code: "PIVOT",
    name: "피벗",
    nameEn: "Pivot",
    nameKo: "피벗",
    route: "/pivot",
    ordinal: 3,
    visible: false,
  },
  {
    id: 15,
    topId: 5,
    code: "DATASET",
    name: "데이터셋",
    nameEn: "Dataset",
    nameKo: "데이터셋",
    route: "/dataset",
    ordinal: 4,
    visible: true,
  },
  {
    id: 16,
    topId: 5,
    code: "QUERY",
    name: "쿼리",
    nameEn: "Query",
    nameKo: "쿼리",
    route: "/query",
    ordinal: 5,
    visible: true,
  },
  {
    id: 43,
    topId: 5,
    code: "PRIVATE_IP",
    name: "내부 IP",
    nameEn: "Private IP",
    nameKo: "내부 IP",
    route: "/private-ip",
    ordinal: 7,
    visible: true,
  },
  {
    id: 48,
    topId: 5,
    code: "PROCEDURE",
    name: "프로시저",
    nameEn: "Procedure",
    nameKo: "프로시저",
    route: "/procedure",
    ordinal: 8,
    visible: true,
  },
  {
    id: 55,
    topId: 5,
    code: "REPORT",
    name: "보고서",
    nameEn: "Report",
    nameKo: "보고서",
    route: "/report",
    ordinal: 9,
    visible: true,
  },
  {
    id: 18,
    topId: 6,

    code: "TICKET",
    name: "티켓",
    nameEn: "Ticket",
    nameKo: "티켓",
    route: "/tickets",
    ordinal: 1,
    visible: true,
  },
  {
    id: 51,
    topId: 6,
    code: "REPOSITORY",
    name: "티켓 분류",
    nameEn: "Repository",
    nameKo: "티켓 분류",
    route: "/tickets/repositories",
    ordinal: 2,
    visible: true,
  },
  {
    id: 19,
    topId: 6,
    code: "EXPLANATION",
    name: "소명",
    nameEn: "Explanation",
    nameKo: "소명",
    route: "/explanation",
    ordinal: 3,
    visible: true,
  },
  {
    id: 20,
    topId: 6,
    code: "EXPLANATION_REVIEW",
    name: "소명 리뷰",
    nameEn: "Explanation Review",
    nameKo: "소명 리뷰",
    route: "/explanation-review",
    ordinal: 4,
    visible: true,
  },
  {
    id: 21,
    topId: 6,
    code: "EXPLANATION_SUBMIT",
    name: "소명 결제",
    nameEn: "Explanation Submit",
    nameKo: "소명 결제",
    route: "/explanation-submit",
    ordinal: 5,
    visible: true,
  },
  {
    id: 22,
    topId: 7,
    code: "STREAM_RULE",
    name: "실시간 탐지",
    nameEn: "Realtime Detection",

    nameKo: "실시간 탐지",
    route: "/stream-rule",
    ordinal: 1,
    visible: true,
  },
  {
    id: 23,
    topId: 7,
    code: "BATCH_RULE",
    name: "배치 탐지",
    nameEn: "Batch Detection",
    nameKo: "배치 탐지",
    route: "/batch-rule",
    ordinal: 2,
    visible: true,
  },
  {
    id: 24,
    topId: 7,
    code: "ML_MODEL",
    name: "머신러닝 모델",
    nameEn: "Machine Learning Model",
    nameKo: "머신러닝 모델",
    route: "/ml-model",
    ordinal: 3,
    visible: true,
  },
  {
    id: 25,
    topId: 7,
    code: "TI_FEED",
    name: "위협 인텔리전스",
    nameEn: "Threat Intelligence",
    nameKo: "위협 인텔리전스",
    route: "/threat-intelligence",
    ordinal: 4,
    visible: true,
  },
  {
    id: 26,
    topId: 7,
    code: "BEHAVIOR_PROFILE",
    name: "행위 프로파일",
    nameEn: "Behavior Profile",
    nameKo: "행위 프로파일",
    route: "/behavior-profile",
    ordinal: 5,
    visible: true,
  },
];

export const emojiMenus = [
  {
    id: 6,
    topId: 3,
    code: "DASHBOARD",
    name: "대시보드",
    nameEn: "Dashboard",
    nameKo: "대시보드",

    route: "/dashboard",
    ordinal: 1,
    visible: true,
    emoji: "🥁",
  },
  {
    id: 7,
    topId: 4,
    code: "CONNECTOR",
    name: "수집 설정",
    nameEn: "Connector",
    nameKo: "수집 설정",
    route: "/connector",
    ordinal: 1,
    visible: false,
    emoji: "🎰",
  },
  {
    id: 8,
    topId: 4,
    code: "PARSER",
    name: "원본 로그 파서 원본 로그 파서 원본 로그 파서 원본 로그 파서",
    nameEn: "Parser",
    nameKo: "원본 로그 파서",
    route: "/parser",
    ordinal: 2,
    visible: false,
    emoji: "🎪",
  },
  {
    id: 46,
    topId: 4,
    code: "NORMALIZER",
    name: "정규화 파서",
    nameEn: "Normalizer",
    nameKo: "정규화 파서",
    route: "/normalizer",
    ordinal: 3,
    visible: true,
    emoji: "🚌",
  },
  {
    id: 9,
    topId: 4,
    code: "SCHEMA",
    name: "정규화",
    nameEn: "Schema",
    nameKo: "정규화",
    route: "/schema",
    ordinal: 4,
    visible: true,
    emoji: "🚗",
  },
  {
    id: 10,
    topId: 4,
    code: "CONNECTOR_MODEL",
    name: "수집 모델",

    nameEn: "Connector Model",
    nameKo: "수집 모델",
    route: "/connector-model",
    ordinal: 5,
    visible: true,
    emoji: "🚠",
  },
  {
    id: 11,
    topId: 4,
    code: "EXTRACTOR_MODEL",
    name: "추출 모델",
    nameEn: "Extractor Model",
    nameKo: "추출 모델",
    route: "/extractor-model",
    ordinal: 6,
    visible: false,
    emoji: "🚖",
  },
  {
    id: 44,
    topId: 5,
    code: "EVENT_SUMMARY",
    name: "탐지 현황",
    nameEn: "Event Summary",
    nameKo: "탐지 현황",
    route: "/event-summary",
    ordinal: 0,
    visible: false,
    emoji: "🥁",
  },
];
